require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/attendance_members", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AttendanceMember. As you add validations to AttendanceMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AttendanceMember.create! valid_attributes
      get attendance_members_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      attendance_member = AttendanceMember.create! valid_attributes
      get attendance_member_url(attendance_member)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_attendance_member_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      attendance_member = AttendanceMember.create! valid_attributes
      get edit_attendance_member_url(attendance_member)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AttendanceMember" do
        expect {
          post attendance_members_url, params: { attendance_member: valid_attributes }
        }.to change(AttendanceMember, :count).by(1)
      end

      it "redirects to the created attendance_member" do
        post attendance_members_url, params: { attendance_member: valid_attributes }
        expect(response).to redirect_to(attendance_member_url(AttendanceMember.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AttendanceMember" do
        expect {
          post attendance_members_url, params: { attendance_member: invalid_attributes }
        }.to change(AttendanceMember, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post attendance_members_url, params: { attendance_member: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested attendance_member" do
        attendance_member = AttendanceMember.create! valid_attributes
        patch attendance_member_url(attendance_member), params: { attendance_member: new_attributes }
        attendance_member.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the attendance_member" do
        attendance_member = AttendanceMember.create! valid_attributes
        patch attendance_member_url(attendance_member), params: { attendance_member: new_attributes }
        attendance_member.reload
        expect(response).to redirect_to(attendance_member_url(attendance_member))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        attendance_member = AttendanceMember.create! valid_attributes
        patch attendance_member_url(attendance_member), params: { attendance_member: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested attendance_member" do
      attendance_member = AttendanceMember.create! valid_attributes
      expect {
        delete attendance_member_url(attendance_member)
      }.to change(AttendanceMember, :count).by(-1)
    end

    it "redirects to the attendance_members list" do
      attendance_member = AttendanceMember.create! valid_attributes
      delete attendance_member_url(attendance_member)
      expect(response).to redirect_to(attendance_members_url)
    end
  end
end
