require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/church_services", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ChurchService. As you add validations to ChurchService, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ChurchService.create! valid_attributes
      get church_services_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      church_service = ChurchService.create! valid_attributes
      get church_service_url(church_service)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_church_service_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      church_service = ChurchService.create! valid_attributes
      get edit_church_service_url(church_service)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ChurchService" do
        expect {
          post church_services_url, params: { church_service: valid_attributes }
        }.to change(ChurchService, :count).by(1)
      end

      it "redirects to the created church_service" do
        post church_services_url, params: { church_service: valid_attributes }
        expect(response).to redirect_to(church_service_url(ChurchService.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ChurchService" do
        expect {
          post church_services_url, params: { church_service: invalid_attributes }
        }.to change(ChurchService, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post church_services_url, params: { church_service: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested church_service" do
        church_service = ChurchService.create! valid_attributes
        patch church_service_url(church_service), params: { church_service: new_attributes }
        church_service.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the church_service" do
        church_service = ChurchService.create! valid_attributes
        patch church_service_url(church_service), params: { church_service: new_attributes }
        church_service.reload
        expect(response).to redirect_to(church_service_url(church_service))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        church_service = ChurchService.create! valid_attributes
        patch church_service_url(church_service), params: { church_service: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested church_service" do
      church_service = ChurchService.create! valid_attributes
      expect {
        delete church_service_url(church_service)
      }.to change(ChurchService, :count).by(-1)
    end

    it "redirects to the church_services list" do
      church_service = ChurchService.create! valid_attributes
      delete church_service_url(church_service)
      expect(response).to redirect_to(church_services_url)
    end
  end
end
